name: Development Build and Deploy

on:
  push:
    branches:
      - 'develop'

env:
  RELEASE_DEPLOY_ENVIRONMENT: 'dev'
  RELEASE_CONTAINER_FULL_NAME: ghcr.io/${{ github.repository }}
  RELEASE_CONTAINER_LABEL: ${{ github.event.repository.name }}
  RELEASE_CONTAINER_FULL_NAME_AND_TAG: ghcr.io/${{ github.repository }}:latest

concurrency:
  group: build-deploy-${{github.ref}}
  cancel-in-progress: false

jobs:
  package-docker-image:
    name: Package Docker Image
    runs-on: ubuntu-latest

    outputs:
      dockerContainerLabel: ${{ github.event.repository.name }}
      releaseDockerImage: ${{ env.RELEASE_CONTAINER_FULL_NAME_AND_TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: '${{ env.RELEASE_CONTAINER_FULL_NAME_AND_TAG }}'

  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    needs: [package-docker-image]
    steps:
      - name: Trigger Deploy Workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{github.repository_owner}}
          repo: ${{github.event.repository.name}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: deploy.yaml
          ref: ${{github.ref}}
          wait_interval: 1
          client_payload: |
            {
              "dockerContainerName": "${{needs.package-docker-image.outputs.dockerContainerLabel}}",
              "dockerImageTag": "${{needs.package-docker-image.outputs.releaseDockerImage}}",
              "environment": "${{ env.RELEASE_DEPLOY_ENVIRONMENT }}"
            }
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: false
