name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        options:
          - dev
          - test
          - prod
        required: true
      dockerContainerName:
        description: 'Docker Container Name'
        required: true
      dockerImageTag:
        description: 'Docker Image and Tag'
        required: true

env:
  MIGRATIONS_DIR: './backend/migrations'
  CONTAINER_TAG: ${{ inputs.dockerImageTag }}
  CONTAINER_LABEL: ${{ inputs.dockerContainerName }}
  ENV_FILE: ${{ vars.ENV_FILE_PATH }}
  PACKAGE_REPO_USERNAME: speedymorales
  PORT: 8080

jobs:
  deploy-backend:
    name: Deploy Docker Image
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{vars.APP_SSH_HOST}}
          username: ${{ vars.APP_SSH_USERNAME }}
          key: ${{secrets.APP_SSH_KEY}} # Private key of the server
          script_stop: true
          script: |
            echo ${{secrets.GHCR_IO_TOKEN}} | docker login ghcr.io -u ${{env.PACKAGE_REPO_USERNAME}} --password-stdin
            docker pull ${{ env.CONTAINER_TAG }}
            docker ps -aq --filter "name=${{ env.CONTAINER_LABEL }}" | xargs -r docker rm -f
            docker run -p ${{env.PORT}}:${{env.PORT}} --network=local_network --env-file ${{env.ENV_FILE}} -d --name=${{ env.CONTAINER_LABEL }} ${{ env.CONTAINER_TAG }}

  migrate-db:
    name: Database Migrations
    needs: deploy-backend
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup DigitalOcean Firewall
        uses: earthpyy/setup-digitalocean-firewall@v1
        with:
          access-token: ${{ secrets.DO_TOKEN }}
          firewall-id: ac019d3f-e127-4e47-99e3-7d6e23e8c7f7
          ports: '3306/tcp'

      - name: Set up Flyway CLI
        run: |
          docker pull flyway/flyway:10.16-alpine
          docker run \
            -v ${{env.MIGRATIONS_DIR}}:/flyway/sql \
            --rm flyway/flyway:10.16-alpine \
            -url=jdbc:mysql://${{vars.DB_DOMAIN}}:${{vars.DB_PORT}}/${{vars.DB_SCHEMA}} \
            -user=${{vars.DB_USER}} \
            -password=${{secrets.DB_PASSWORD}} \
            -locations=filesystem:/flyway/sql \
            migrate
