name: Promote

on:
  workflow_dispatch:

env:
  RELEASE_DEPLOY_ENVIRONMENT: 'prod'
  RELEASE_CONTAINER_FULL_NAME: ghcr.io/${{ github.repository }}
  RELEASE_CONTAINER_LABEL: ${{ github.event.repository.name }}

concurrency:
  group: build-release-${{github.ref}}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release Version
        id: release-info
        run: |
          RELEASE_VERSION=v$(jq -r '.version' ./package.json)
          echo "releaseVersion=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "releaseVersion=$RELEASE_VERSION"

          RELEASE_VERSION_STRICT=$(jq -r '.version' ./package.json)
          echo "releaseVersionStrict=$RELEASE_VERSION_STRICT" >> $GITHUB_OUTPUT
          echo "releaseVersionStrict=$RELEASE_VERSION_STRICT"

      - name: Trigger Deploy Workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{github.repository_owner}}
          repo: ${{github.event.repository.name}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: deploy.yaml
          ref: ${{github.ref}}
          wait_interval: 1
          client_payload: |
            {
              "dockerContainerName": "${{env.RELEASE_CONTAINER_LABEL}}",
              "dockerImageTag": "${{env.RELEASE_CONTAINER_FULL_NAME}}:${{steps.release-info.outputs.releaseVersionStrict}}",
              "environment": "${{ env.RELEASE_DEPLOY_ENVIRONMENT }}"
            }
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: false
