name: Build and Test on PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run prettier
      - run: npm run lint
      - run: npm run test:cov
      - run: npm run build
